### ISSUE TITLE
Expand the capability of tool to also work for .docx / .doc files (i.e. Microsoft Word files)

### ISSUE THREAD

**Issue by suraj-singh12** [suraj-singh12/Project-SearchEverywhere#1]
### Summary : 
When there are Microsoft Word Documents (.docx or .doc) also present in the directory, the tool must also look into them, to search for the information.

**One way to achieve this is:**
* Convert all .docx or .doc files to .odt (LibreOffice writer files) 
* Store those files in the same directory, and then run the tool

_There may be other ways too, so feel free to try out any new idea you may have._

Ensure: 

- [ ] Your code does not breaks the previous functionalities of tool

- [ ] It adds the required functionality [support for .docx / .doc files]

- [ ] It has been tested on a bunch of [.docx / .doc files]

- [ ] The code is neat, and well commented when required

**Comment by Alireza-Sampour** [comment]
Can I work on this?

**Comment by suraj-singh12** [comment]
yes @Alireza-Sampour 
I have assigned it to you.

**Comment by Alireza-Sampour** [comment]
@suraj-singh12 I created a pull request for it.

**Comment by suraj-singh12** [comment]
I am reviewing your code, and will update you soon
