### ISSUE TITLE
/usr/bin/python3^M: bad interpreter [error while running the src script]

### ISSUE THREAD

**Issue by rider577** [suraj-singh12/Project-SearchEverywhere#11]
When following the directions in ```CONTRIBUTING.md```, step 6 results following error:

```bash: ./SearchEverywhere.py: /usr/bin/python3^M: bad interpreter: No such file or directory```

**Comment by suraj-singh12** [comment]
That is basically a line endings issue.

**Comment by suraj-singh12** [comment]
I have fixed this in the recent commit. You can test it and provide me with feedback.

**Comment by rider577** [comment]
yes, it is fixed.
