### ISSUE TITLE
Expand the capability of tool to also work for .pptx / .ppt files (i.e. Microsoft PowerPoint files) 

### ISSUE THREAD

**Issue by suraj-singh12** [suraj-singh12/Project-SearchEverywhere#2]
### Summary  :
When there are Microsoft PowerPoint Presentations (.pptx or .ppt) also present in the directory, the tool must also look into them, to search for the information.

**One way to achieve this is:**

Convert all .pptx or .ppt files to .odt (LibreOffice Impress files)
Store those files in the same directory, and then run the tool

_There may be other ways too, so feel free to try out any new idea you may have._

Ensure:
- [ ] Your code does not breaks the previous functionalities of tool

- [ ] It adds the required functionality [support for .pptx / .ppt files]

- [ ] It has been tested on a bunch of [.pptx / .ppt files]

- [ ] The code is neat, and well commented when required

**Comment by DevChoganwala** [comment]
Hey @suraj-singh12, I would like to work on this issue!

**Comment by suraj-singh12** [comment]
go ahead @DevChoganwala 
I have assigned you this issue.

**Comment by suraj-singh12** [comment]
Are you working on this @DevChoganwala ?
If yes, kindly update with how much progress you've made.

**Comment by DevChoganwala** [comment]
Hey @suraj-singh12, I am done with ppt part, I am working on resolving some errors with the pptx part, can expect to be completed today itself!

**Comment by suraj-singh12** [comment]
Sure, take your time.
