### ISSUE TITLE
Support other GNU/linux distros

### ISSUE THREAD

**Issue by Shubham-Vy** [suraj-singh12/Project-SearchEverywhere#8]
I want this tool to work on other linux distros like Arch Linux Void Linux and Gentoo Linux

**Comment by suraj-singh12** [comment]
Can you specify which Linux distros you want the tool to work?

Currently, I have tested it on Ubuntu, Debian, and Fedora.
I believe, it should work on all Debian and Arch-based distros.

**Comment by suraj-singh12** [comment]
@Shubham-Vy Can you specify which other Linux distros you want the tool to work with?
Currently, I have tested it on Ubuntu, Debian, and Fedora.

**Comment by Shubham-Vy** [comment]
void linux , gentoo linux and other arch-based distros

**Comment by suraj-singh12** [comment]
Have you tried to install it on any of these distros until now?

**Comment by Shubham-Vy** [comment]
yeah I tried it on artix linux (arch-based)
[Screen Shot](https://cdn.discordapp.com/attachments/831977669272797215/893895007512174593/unknown.png)

**Comment by Shubham-Vy** [comment]
btw if you don't mind I can write a bash script(for deps) for this project which will run on most linux distros like arch and other arch-based

**Comment by suraj-singh12** [comment]
yes, @Shubham-Vy I am assigning you this beautiful task of making a bash script for arch dependencies.
